global using Application.Contracts.Persistence;
global using Domain.Entities;
global using Infrastructure.Persistence;
global using Microsoft.EntityFrameworkCore;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Threading.Tasks;
